module SocialsRegex
  class Regexes
    ANGELLIST_URL_REGEX: Hash[Symbol, Regexp]
    CRUNCHBASE_URL_REGEX: Hash[Symbol, Regexp]
    EMAIL_URL_REGEX: Hash[Symbol, Regexp]
    FACEBOOK_URL_REGEX: Hash[Symbol, Regexp]
    GITHUB_URL_REGEX: Hash[Symbol, Regexp]
    HACKERNEWS_URL_REGEX: Hash[Symbol, Regexp]
    INSTAGRAM_URL_REGEX: Hash[Symbol, Regexp]
    LINKEDIN_URL_REGEX: Hash[Symbol, Regexp]
    MEDIUM_URL_REGEX: Hash[Symbol, Regexp]
    PHONE_URL_REGEX: Hash[Symbol, Regexp]
    REDDIT_URL_REGEX: Hash[Symbol, Regexp]
    SKYPE_URL_REGEX: Hash[Symbol, Regexp]
    SNAPCHAT_URL_REGEX: Hash[Symbol, Regexp]
    STACKEXCHANGE_NETWORK_URL_REGEX: Hash[Symbol, Regexp]
    STACKEXCHANGE_URL_REGEX: Hash[Symbol, Regexp]
    STACKOVERFLOW_URL_REGEX: Hash[Symbol, Regexp]
    TELEGRAM_URL_REGEX: Hash[Symbol, Regexp]
    TWITTER_URL_REGEX: Hash[Symbol, Regexp]
    VIMEO_URL_REGEX: Hash[Symbol, Regexp]
    XING_URL_REGEX: Hash[Symbol, Regexp]
    YOUTUBE_URL_REGEX: Hash[Symbol, Regexp]
  end
end
